### ISSUE TITLE
Cleanup of Overflow files

### ISSUE THREAD

**Issue by dfordivam** [haskell-haskey/haskey#70]
Hello

Thanks for the great library! I really like this as it helps me avoid all the DB marshaling boilerplate..

One thing I realized after using this for a while that the overflow pages keep on accumulating.
I am using a nested tree structure, and therefore the size of overflow pages becomes quite large whenever a part of the data changes.

Is there a way to do regular cleanups? or avoid this problem all together?

**Comment by dfordivam** [comment]
Oh I see some closed tickets already mentioning this issue.. has this been fixed already?

**Comment by dfordivam** [comment]
Ok I have now tried with the latest code and I still see this issue.

I think this issue might be due to a nested tree
the total size of the db is about 7.4mb, and after some write to db, I see multiple overflow files adding to 540mb.

```
7.3M    srsdb/overflow/f0/0
7.4M    srsdb/overflow/f0
36K     srsdb/overflow/a2/0
40K     srsdb/overflow/a2
7.3M    srsdb/overflow/ff/0
7.4M    srsdb/overflow/ff
7.3M    srsdb/overflow/eb/0
7.4M    srsdb/overflow/eb
7.3M    srsdb/overflow/cc/0
7.4M    srsdb/overflow/cc
```

**Comment by hverr** [comment]
@dfordivam Let me look into this! I'll run some experiments!

**Comment by dfordivam** [comment]
Thanks!

I changed my db to non-nested form and still see this issue..

**Comment by dfordivam** [comment]
Hello were you able to reproduce this issue?

Should I do anything to help here?

And is there any work around?
I guess writing a new db on close and removing the previous one is one... although while the db is open it can still take huge amount to space.

**Comment by hverr** [comment]
@dfordivam  I was able to reproduce the issue. Will be debugging it later today to find a fix.

For future reference: minimal example, which lets the database grow indefinitely:

```haskell
#!/usr/bin/env stack
{- stack --resolver lts-9.0
         --install-ghc
         runghc
         --package haskey-0.2.0.0
         --package haskey-btree-0.2.0.0
         --package haskey-mtl-0.2.0.0
-}
module Main where

import Control.Monad
import Control.Monad.IO.Class
import Control.Monad.Haskey

import Data.ByteString (ByteString)
import Data.Int
import Data.BTree.Alloc (AllocM)
import Data.BTree.Impure
import qualified Data.BTree.Impure as Tree
import qualified Data.ByteString as BS

import System.Directory (doesPathExist, removeDirectoryRecursive)
import System.IO (IOMode(ReadMode), withFile)

type Schema = Tree Int64 ByteString

main :: IO ()
main = do
    db <- create
    runHaskeyT app db defFileStoreConfig

create :: IO (ConcurrentDb Schema)
create = do
    e <- doesPathExist databaseFilePath
    when e $ removeDirectoryRecursive databaseFilePath
    runFileStoreT action defFileStoreConfig
  where
    action = let handles = concurrentHandles databaseFilePath in
             createConcurrentDb handles Tree.empty

app :: HaskeyT Schema IO ()
app = mapM_ deleteInsertCycle [1..20]

deleteInsertCycle :: Int64 -> HaskeyT Schema IO ()
deleteInsertCycle i = do
    v <- liftIO $ do
        putStrLn $ "Cycle " ++ show i
        withFile "/dev/urandom" ReadMode $ flip BS.hGet (5*1024*1024)
    transact_ (deleteOld >=> insertNew v >=> commit_)
  where
    insertNew :: AllocM m => ByteString -> Schema -> m Schema
    insertNew = insertTree i

    deleteOld :: AllocM m => Schema -> m Schema
    deleteOld = deleteTree (i-1)

databaseFilePath :: FilePath
databaseFilePath = "test.db"
```

**Comment by hverr** [comment]
Update: previous minimal code example fixed in following patches:

- haskey: haskell-haskey/haskey@0ee7f11cb9b687441b73b968b602f6fb9ff66612
- haskey-btree: haskell-haskey/haskey-btree@ae4f3c9865ac96c2bcfda879ee4f98decb9061aa

**Comment by hverr** [comment]
Update: this solves directly deleting values with overflow pages attached, but does not solve overwriting values with overflow pages attached.

The following minimal code example still makes the database grow indefinitely:

```haskell
#!/usr/bin/env stack
{- stack --resolver lts-9.0
         --install-ghc
         runghc
         --package haskey-0.2.0.0
         --package haskey-btree-0.2.0.0
         --package haskey-mtl-0.2.0.0
-}
module Main where

import Control.Monad
import Control.Monad.IO.Class
import Control.Monad.Haskey

import Data.ByteString (ByteString)
import Data.Int
import Data.BTree.Alloc (AllocM)
import Data.BTree.Impure
import qualified Data.BTree.Impure as Tree
import qualified Data.ByteString as BS

import System.Directory (doesPathExist, removeDirectoryRecursive)
import System.IO (IOMode(ReadMode), withFile)

type Schema = Tree Int64 ByteString

main :: IO ()
main = do
    db <- create
    runHaskeyT app db defFileStoreConfig

create :: IO (ConcurrentDb Schema)
create = do
    e <- doesPathExist databaseFilePath
    when e $ removeDirectoryRecursive databaseFilePath
    runFileStoreT action defFileStoreConfig
  where
    action = let handles = concurrentHandles databaseFilePath in
             createConcurrentDb handles Tree.empty

app :: HaskeyT Schema IO ()
app = mapM_ insertCycle [1..20]

insertCycle :: Int -> HaskeyT Schema IO ()
insertCycle i = do
    v <- liftIO $ do
        putStrLn $ "Cycle " ++ show i
        withFile "/dev/urandom" ReadMode $ flip BS.hGet (5*1024*1024)
    transact_ (insertNew v >=> commit_)
  where
    insertNew :: AllocM m => ByteString -> Schema -> m Schema
    insertNew = insertTree 0

databaseFilePath :: FilePath
databaseFilePath = "test.db"
```

**Comment by hverr** [comment]
Update: following patch solves the previous minimal code example. This solves deleting overflow pages attached to overwritten keys when inserting.

haskell-haskey/haskey-btree@99c6a6d93a53d9bc0b2f9bf2256fd6d8ecf373b3

**Comment by hverr** [comment]
Previous patches incorporated in linked pull requests:
1. haskell-haskey/haskey-btree#3
2. haskell-haskey/haskey#71

**Comment by hverr** [comment]
Updated packages on hackage:

1. [haskey-btree-0.2.0.1](https://hackage.haskell.org/package/haskey-btree-0.2.0.1)
1. [haskey-0.2.0.1](https://hackage.haskell.org/package/haskey-0.2.0.1)

@dfordivam Can you check if this resolves your issue?

**Comment by dfordivam** [comment]
It seems the issue is resolved... Thanks for a quick fix!

**Comment by hverr** [comment]
No problem! Glad to hear you like the library!
