### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by LeanderK** [haskell-haskey/haskey#73]
I know it's not exactly stable, but I might plan to rely on haskey on a project (itself experimental, so not production-stuff).

Haskey will only handle relatively short-lived, temporary data, so I don't really care too much about the issue i #72. If there's some corruption, I can just recalculate everything. I know Haskey it's not rock-solid.

But I want to avoid getting myself familiar with and using a completely abandoned project.

**Comment by hverr** [comment]
Hey Leander, we are definitely not planning on abandoning this project. However, currently me and @skeuchel are very busy in our day-to-day lives which causes some delay in our response times.

**Comment by LeanderK** [comment]
no problem! 🙂 I was just wondering. Thank you!
