### ISSUE TITLE
How does performance compare to LMDB/LevelDB etc?

### ISSUE THREAD

**Issue by yairchu** [haskell-haskey/haskey#76]
Hi!

I didn't notice anything comparing the performance of `haskey` with other solutions, except for it being modelled after LMDB which implies that it should be pretty fast.

So [I tried using `haskey`](https://github.com/lamdu/lamdu/commit/4ef10ba79d449aeb8dbc8455661c2455bf6225c1) instead of [`leveldb-haskell`](http://hackage.haskell.org/package/leveldb-haskell) which I'm currently using (due to having problems with building LevelDB on Windows), and my application's performance became significantly worse.
I didn't produce numbers because it's an interactive application, whose responsiveness became noticeably sluggish when transitioning to `haskey`. But I guess we could do that.

I just wonder if `haskey` tries to have competitive performance? Am I simply using it wrong?

**Comment by hverr** [comment]
You are probably not using it wrongly. Haskey is not optimised for performance and not suited for low latency or high throughput needs.

The internal design is the same as LMDB, but internal algorithms are suboptimally implemented.
